### ISSUE TITLE
Newer Version?

### ISSUE THREAD

**Issue by EAWF** [coinables/buidljs#17]
Do you have plans to upgrade this version and to document the fromXPub function?

Is there another version of buidljs that is newer than this one and has the fromXPub function working and documented?

**Comment by coinables** [comment]
Yes I do plan to. I have a newer version I need to merge with this repo. 

https://coinables.github.io/buidljs/ 
This page uses the newer version that goes from mnemonic to seed, seed to xpub/ypub/zpub, and then the fromXpub just takes xpub,ypub,zpub, a change account and index for derivation.

**Comment by EAWF** [comment]
JUST what I've been looking for! Thanks!
