### ISSUE TITLE
Issues in Chrome?

### ISSUE THREAD

**Issue by steffanjensen** [coinables/buidljs#3]
Hi I have issues generating keys in chrome, it works fine in Firefox. 

Tested with over 5 different pc's and networks and all same error with chrome ?

Error in chrome

buidl.js:1 Uncaught SyntaxError: Invalid or unexpected token
taa.html:6 Uncaught ReferenceError: buidl is not defined
    at taa.html:6

This is how chrome sees the code
(function(f){if(typeof攀砀瀀漀爀琀猀㴀㴀

**Comment by coinables** [comment]
I am using this exclusively in chrome with no issues. Can you share more of your source so I can see if I can re-create it on my machine?

**Comment by reliefs** [comment]
https://wallet.brominer.com/taa.html

**Comment by coinables** [comment]
Works fine for me https://s8.postimg.cc/z7qypq4ud/Untitled.png What OS are you using?

**Comment by steffanjensen** [comment]
Linux, But my friend had the same issue on Windows. 

All chrome users, in my user database i can see the script is only working 20% of the time. 

Edit: Now the script works for me with chrome (i have changed nothing) weird. 

Edit2: But i can see my users are still having the problem, script is only genrating a key 20% of the time. 

Edit3: Just tested the register page, and i'm still getting the issue with chrome there. 

reg.php:14 Uncaught ReferenceError: buidl is not defined
    at reg.php:14
(anonymous) @ reg.php:14
reg.php:61 Uncaught ReferenceError: newPair is not defined
    at reg.php:61

No erros with Firefox on the same page.

EDit4: Not getting the error anymore saving buidls in UEFI-8 i will test to see if it work.

**Comment by steffanjensen** [comment]
Tested with over 20 users no errors so far. For people having the same issue. 

Save buidl in Uefi-8.

**Comment by coinables** [comment]
Glad you got it to work. 

As a side note, since I saw you mentioned users and registering, this is a front-end only javascript wrapper for bitcoinjs-lib. I would advise against trying to implement it in a live and open environment.  This is intended more as a personal use tool or to build web tools, like coinb.in, or bip32.org.  I'm  not trying to be a bummer, just wanted to warn you.
