### ISSUE TITLE
Request: BIP32 Xpub To Payment Address Function

### ISSUE THREAD

**Issue by EAWF** [coinables/buidljs#4]
@coinables, is this something that could be included in buidl.js, or would you want it to be in a separate library?

**Comment by coinables** [comment]
I started with some of the HD functions but haven't included them in the READ_ME yet. 
See: 
https://github.com/coinables/buidljs/blob/master/create.js#L365
https://github.com/coinables/buidljs/blob/master/create.js#L373

**Comment by EAWF** [comment]
I started my own repository for the algorithm and production code for the derivation process at [Bitcoin Merchant's Toolbox](https://github.com/EAWF/Bitcoin-Merchants-Toolbox)
