### ISSUE TITLE
P2WPKH addresses are not valid

### ISSUE THREAD

**Issue by stl1988** [coinables/buidljs#6]
When I try to check a generated P2WPKH address on blockchain.com (former blockchain.info), it says "Illegal charakter 0 at position X" (where X is a certain position in the address).

**Comment by coinables** [comment]
Considering its base 58 format this should be very simple... It would help if you told us what character it's saying is illegal. Also make sure you're not copying and pasting spaces or other weird characters.

**Comment by stl1988** [comment]
P2WPKH should not be confused with P2PKH, which is indeed Base58. P2WPKH are Segwit addresses using the new bech32 format. This is where the problem is. All Base58 addresses work just fine. Only the bech32 ones don't. Also for each generated bech32 address Blockchain.com always lists different illegal charakters at different positions. But no charakter which isn't allowed in bech32.

**Comment by coinables** [comment]
Blockchain.com does not support bech32. They philosophically oppose it. I
don't use them anymore neither should you or anyone for that matter.

**Comment by stl1988** [comment]
I've just noticed. Deep sorry because of that.
