### ISSUE TITLE
Create transaction

### ISSUE THREAD

**Issue by Sinawm** [coinables/buidljs#7]
Hi coinables,
How are you?
I'm a little noob geek and i want to know:
1) how can i make transactions?
2) what is transaction hash?
And last) how can i check the balance???

**Comment by Sinawm** [comment]
And what is different between signedtx and taxid and transaction id???
Excuse me im so dumb.

**Comment by coinables** [comment]
tx is shorthand for transaction. 
A signed transaction is what you create and sign before broadcasting. 
A transaction id is a hash of the raw transaction. 

Creating a transaction is described in section 5 of the README. 

`createTransaction("3", "34eceJ...", 0, "1P5Ef7FsaD1KsJNSTUcACceEWN9vsUe3eN", 350000, "L1RLQhjuGoQ37QP4jfaEFTHMuEUeh4JdUDkx32xeafhnpzRMDMXD", null, null, 4000000)`
