### ISSUE TITLE
Safe to Use for production?

### ISSUE THREAD

**Issue by EAWF** [coinables/buidljs#8]
Seems there are stable versions which are safe for production at [bitcoinjs-lib](https://github.com/bitcoinjs/bitcoinjs-lib#should-i-use-this-in-production).

Are you using one of these versions for buidljs, and if so, which version are you using?

**Comment by coinables** [comment]
Buidljs uses version 3.2 of bitcoinjs.  Version 3.2 is a stable tagged release.  https://github.com/coinables/buidljs/blob/master/node_modules/bitcoinjs-lib/CHANGELOG.md
